<?php
/**
 * Class Admin_Page
 *
 * Registers the PGBF Pro tab in WooCommerce → Settings and renders the React SPA.
 *
 * @package checkout-fees-for-woocommerce
 */

namespace TycheSoftwares\PaymentGatewayFees\Lite;

defined( 'ABSPATH' ) || exit;

/**
 * Class Admin_Page
 *
 * Handles the admin settings page for Payment Gateway Fees.
 */
class Admin_Page {

	/**
	 * Settings tab ID.
	 *
	 * @var string
	 */
	const TAB_ID = 'payment-gateway-fees-for-woocommerce';

	/**
	 * Constructor.
	 */
	public function __construct() {
		add_filter( 'woocommerce_settings_tabs_array', array( $this, 'add_settings_tab' ), 50 );
		add_action( 'woocommerce_settings_' . self::TAB_ID, array( $this, 'render_settings_tab' ) );
		add_action( 'woocommerce_settings_save_' . self::TAB_ID, '__return_false' );
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_assets' ) );
	}

	/**
	 * Add settings tab to WooCommerce settings array.
	 *
	 * @param array<string, string> $tabs Existing settings tabs.
	 * @return array<string, string> Modified tabs.
	 */
	public function add_settings_tab( array $tabs ): array {
		$tabs[ self::TAB_ID ] = __( 'Payment Gateway Fees', 'checkout-fees-for-woocommerce' );
		return $tabs;
	}

	/**
	 * Render the settings tab content.
	 */
	public function render_settings_tab(): void {
		echo '<div id="pgbf-settings-root"></div>';
	}

	/**
	 * Enqueue assets for the settings page.
	 *
	 * @param string $hook_suffix Current admin page hook suffix.
	 */
	public function enqueue_assets( string $hook_suffix ): void {

		if ( 'woocommerce_page_wc-settings' !== $hook_suffix ) {
			return;
		}

		// phpcs:ignore WordPress.Security.NonceVerification.Recommended
		$current_tab = isset( $_GET['tab'] ) ? sanitize_key( wp_unslash( $_GET['tab'] ) ) : '';

		if ( self::TAB_ID !== $current_tab ) {
			return;
		}

		$asset_file = PGBF_LITE_PLUGIN_PATH . '/build/settings.asset.php';

		if ( file_exists( $asset_file ) ) {

			$asset = require $asset_file;

			/**
			 * Register the fake CSS handle generated by @wordpress/scripts.
			 * Without this WordPress silently drops the script entirely.
			 */
			wp_register_style(
				'wp-components/build-style/style.css',
				false,
				array( 'wp-components' ),
				$asset['version']
			);

			wp_enqueue_style(
				'pgbf-pro-settings',
				PGBF_LITE_PLUGIN_URL . '/build/settings.css',
				array(
					'wp-components',
					'wp-components/build-style/style.css',
					'woocommerce_admin_styles',
				),
				$asset['version']
			);

			wp_enqueue_style( 'dashicons' );

			wp_enqueue_script(
				'pgbf-pro-settings',
				PGBF_LITE_PLUGIN_URL . '/build/settings.js',
				$asset['dependencies'],
				$asset['version'],
				true
			);

			wp_set_script_translations(
				'pgbf-pro-settings',
				'checkout-fees-for-woocommerce',
				PGBF_LITE_PLUGIN_PATH . '/languages'
			);

			// Inject the REST nonce so wp.apiFetch can authenticate.
			wp_add_inline_script(
				'wp-api-fetch',
				sprintf(
					'wp.apiFetch.use( wp.apiFetch.createNonceMiddleware( %s ) );',
					wp_json_encode( wp_create_nonce( 'wp_rest' ) )
				),
				'after'
			);

			wp_localize_script(
				'pgbf-pro-settings',
				'pgbfProData',
				array(
					'restUrl'  => esc_url_raw( rest_url( 'pgbf-pro/v1/' ) ),
					'adminUrl' => esc_url_raw( admin_url() ),
					'version'  => PGBF_LITE_PLUGIN_VERSION,
				)
			);
			
		}
	}
}